export const movies = [
  {
    id: '1',
    title: 'Interstellar Odyssey',
    genre: 'Sci-Fi',
    language: 'English',
    rating: 9.1,
    duration: '2h 49m',
    price: 14.99,
    description:
      'A crew of astronauts travels through a newly discovered wormhole in search of a new home for humanity, pushing the limits of time and space in a breathtaking journey across the cosmos.',
    cast: ['Matthew Reynolds', 'Anne Clarke', 'Jessica Wade', 'Michael Caine'],
    showtimes: ['10:00 AM', '1:30 PM', '5:00 PM', '8:30 PM'],
    posterEmoji: '🚀',
  },
  {
    id: '2',
    title: 'Crimson Blade',
    genre: 'Action',
    language: 'English',
    rating: 8.4,
    duration: '2h 12m',
    price: 12.99,
    description:
      'An elite assassin uncovers a global conspiracy that puts her own organisation in the crosshairs. With nowhere left to run, she must fight through an empire of shadows to survive.',
    cast: ['Sofia Reyes', 'Idris Khan', 'Liam Foster', 'Zara Huang'],
    showtimes: ['11:00 AM', '2:15 PM', '6:45 PM', '9:30 PM'],
    posterEmoji: '⚔️',
  },
  {
    id: '3',
    title: 'Neon Ghosts',
    genre: 'Thriller',
    language: 'English',
    rating: 8.7,
    duration: '1h 58m',
    price: 13.49,
    description:
      'In a rain-soaked cyberpunk city, a detective haunted by her past investigates a series of impossible murders that blur the line between the digital and physical worlds.',
    cast: ['Priya Sharma', 'Kaito Mori', 'Elena Vasquez', 'Tom Bellamy'],
    showtimes: ['12:00 PM', '3:30 PM', '7:00 PM', '10:00 PM'],
    posterEmoji: '🌆',
  },
  {
    id: '4',
    title: 'The Last Horizon',
    genre: 'Drama',
    language: 'English',
    rating: 8.9,
    duration: '2h 22m',
    price: 11.99,
    description:
      "Two strangers meet on a cross-country train journey and over five days change each other's lives forever, forcing them both to confront the choices that define who they truly are.",
    cast: ['Clara Fontaine', 'Marcus Webb', 'Diana Chen', 'Robert Okafor'],
    showtimes: ['10:30 AM', '1:00 PM', '4:30 PM', '7:30 PM'],
    posterEmoji: '🌅',
  },
  {
    id: '5',
    title: 'Shadow Protocol',
    genre: 'Action',
    language: 'English',
    rating: 7.8,
    duration: '2h 5m',
    price: 12.49,
    description:
      'A rogue intelligence agent races against the clock to stop a terrorist cell from deploying a bio-weapon capable of wiping out an entire continent — with no backup and zero resources.',
    cast: ['Jake Mercer', 'Anya Petrov', 'Liu Wei', 'Carlos Mendez'],
    showtimes: ['9:30 AM', '12:45 PM', '4:00 PM', '8:00 PM'],
    posterEmoji: '🕵️',
  },
  {
    id: '6',
    title: 'Echoes of Eternity',
    genre: 'Fantasy',
    language: 'English',
    rating: 8.2,
    duration: '2h 35m',
    price: 13.99,
    description:
      'A young sorceress must unite warring kingdoms by uncovering ancient magic buried beneath a dying world — but the price of that power may be greater than anything she imagined.',
    cast: ['Isla Grant', 'Finn Calloway', 'Mira Osei', 'Aldric Stone'],
    showtimes: ['11:30 AM', '3:00 PM', '6:00 PM', '9:00 PM'],
    posterEmoji: '🧙',
  },
  {
    id: '7',
    title: 'Velocity',
    genre: 'Action',
    language: 'English',
    rating: 7.5,
    duration: '1h 52m',
    price: 11.49,
    description:
      'Street racer turned reluctant hero, Dex must outrun a criminal syndicate across three cities using nothing but his legendary driving skill and a battered, supercharged muscle car.',
    cast: ['Diego Fuentes', 'Kenji Watanabe', 'Aisha Oduya', 'Sam Price'],
    showtimes: ['10:00 AM', '1:15 PM', '5:30 PM', '8:45 PM'],
    posterEmoji: '🏎️',
  },
  {
    id: '8',
    title: 'Deep Blue Fear',
    genre: 'Horror',
    language: 'English',
    rating: 7.9,
    duration: '1h 47m',
    price: 10.99,
    description:
      'A marine biologist and her crew on a deep-sea research vessel awaken something ancient and terrifying from the ocean floor. Now, miles from shore, survival is not guaranteed.',
    cast: ['Nina Frost', 'Caleb Storm', 'Lena Marsh', 'Henry Vance'],
    showtimes: ['12:30 PM', '4:00 PM', '7:30 PM', '10:30 PM'],
    posterEmoji: '🦑',
  },
  {
    id: '9',
    title: 'Laughing Stock',
    genre: 'Comedy',
    language: 'English',
    rating: 7.3,
    duration: '1h 38m',
    price: 9.99,
    description:
      'When a small-town butcher accidentally becomes an overnight internet sensation, he must navigate sudden fame, a frantic talent manager, and his extremely opinionated family.',
    cast: ['Barry Hill', 'Gina Romano', 'Phil Watts', 'Daisy Park'],
    showtimes: ['11:00 AM', '2:00 PM', '5:15 PM', '8:00 PM'],
    posterEmoji: '😂',
  },
  {
    id: '10',
    title: 'Fracture Point',
    genre: 'Thriller',
    language: 'English',
    rating: 8.5,
    duration: '2h 8m',
    price: 13.49,
    description:
      'A forensic psychologist is called in to negotiate with a genius hostage-taker who has locked down a city skyscraper — only to discover the real game is being played elsewhere entirely.',
    cast: ['Evelyn Cross', 'Nathan Fox', 'Amara Diallo', 'Viktor Sorin'],
    showtimes: ['10:45 AM', '2:30 PM', '6:15 PM', '9:45 PM'],
    posterEmoji: '🧠',
  },
];

export const seatLayout = [
    {row: "A", seats: [1,2,3,4,5,6,7,8,9,10], booked: [3,8] },
    { row: "B", seats: [1,2,3,4,5,6,7,8,9,10], booked: [1,2] },
    { row: "C", seats: [1,2,3,4,5,6,7,8,9,10], booked: [5,6,9] },
    { row: "D", seats: [1,2,3,4,5,6,7,8,9,10], booked: [4] },
    { row: "E", seats: [1,2,3,4,5,6,7,8,9,10], booked: [8,10] },
    { row: "F", seats: [1,2,3,4,5,6,7,8,9,10], booked: [2,3,7] },
    { row: "G", seats: [1,2,3,4,5,6,7,8,9,10], booked: [1,5] },
    { row: "H", seats: [1,2,3,4,5,6,7,8,9,10], booked: [6,9,10] },
]

export const bookings = [
    {
        id: "BK01",
        movieTittle: "Interstellar Odyssey",
        date: "2026-12-15",
        showtime: "5:00 PM",
        seats: ["A4", "A5"],
        totalPrice: 620,
        name: "Zoe",
        email: "test1@test.com"
    },
    {
        id: "BK002",
    movieTitle: "Crimson Blade",
    date: "2026-12-18",
    showtime: "9:30 PM",
    seats: ["C3", "C4", "C5"],
    totalPrice: 850,
    name: "Rahul Sharma",
    email: "rahul@example.com"
  },
  {
    id: "BK003",
    movieTitle: "Neon Ghosts",
    date: "2026-12-20",
    showtime: "7:00 PM",
    seats: ["F2", "F3"],
    totalPrice: 420,
    name: "Rahul Sharma",
    email: "rahul@example.com"
  }
    
]